### ISSUE TITLE
inet_pton() returned error with IPv6

### ISSUE THREAD

**Issue by sebix** [hadiasghari/pyasn#14]
Both with Python 2 and Python 3 I encounter this error with IPv6 addresses, while IPv4 works fine:

    >>> db.lookup('8.8.8.8')
    (15169, '8.8.8.0/24')
    >>> db.lookup('2001:500:88:200::8')
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/local/lib/python3.4/dist-packages/pyasn/__init__.py", line 83, in lookup
        rn = self.radix.search_best(ip_address)
    ValueError: inet_pton() returned error

This IPv6 address is from iana.org, so should be valid.

    pyasn==1.5.0b6

Database is also fresh: `rib.20150901.1400.bz2`

**Comment by hadiasghari** [comment]
Hi Sebix, and thanks for the bug report. We hadn't tested the IPv6 functionality yet - basically that's what's holding back coming out of 'beta'. The underlying radix tree supports IPv6, so the rest shouldn't be too hard to fix once we get to it. If you're in a hurry, I'd suggest you look for another module. If you have a few weeks, I can get on to it and fix the IPv6 part after a few other projects on my plate are done.

Just also for the record, could you tell your Platform? From the error it seems Python 3.4 on Windows; Did you install it via pip? What is your build environment (e.g. GCC or Visual Studio, etc)?

**Comment by sebix** [comment]
No, I use Linux (based on ubuntu 14.04 LTS). Installed via pip and uses 2.7 and 3.4.

Btw, it's used in [certtools/intelmq](https://github.com/certtools/intelmq/), I discovered the bug during developing/testing the software.

**Comment by hadiasghari** [comment]
Great to know that it's combined with this other package; I'll prioritize it on our side for the next cycles. Do you have examples of actual IPv6 addresses that will be looked up (useful for debugging)? So far few public blacklists I've seen include IPv6 addresses. Thanks.

**Comment by sebix** [comment]
Here are some addresses you can use:

    "2001:250:1001:1851:116:756d:e2f0:11a1"
    "2001:41d0:2:3c2d::1"
    "2001:41d0:52:100::1341"
    "2001:41d0:a:6a9d::1"
    "2001:e42:102:1208:153:121:75:130"
    "2607:5300:100:200::e66"
    "2607:5300:60:623c::"
    "2607:ff50:0:37:250:56ff:febe:4d8a"
    "2a01:6f0:ffff:f7::5c78"
    "2a01:7e00::f03c:91ff:fe73:f5d9"
    "2a02:c200:1:10:2:3:7159:1"
    "2001:41d0:2:3c2d::1"
    "2001:41d0:2:e97a::"
    "2001:4800:7819:101:be76:4eff:fe01:c865"
    "2400:8900::f03c:91ff:fe50:cdaa"
    "2607:5300:60:75b6::"
    "2a00:7143:102:101:216:3eff:fe9f:bef8"
    "2a02:c200:1:10:2:3:7159:1"
    "2001:41d0:1:7f3e::1"
    "2001:41d0:1:e95e::1"
    "2001:41d0:2:7a6::1"
    "2001:41d0:d:50f::"
    "2001:4d80:600:63:a4ed:6d9:fed5:a5eb"
    "2002:17ee:f502::17ee:f502"
    "2002:2d21:f4a2::2d21:f4a2"
    "2002:2d22:b585::2d22:b585"
    "2002:2d22:b586::2d22:b586"
    "2002:2d22:b588::2d22:b588"
    "2002:2d29:5032::2d29:5032"
    "2002:4275:93c::4275:93c"
    "2002:5bc8:c24::5bc8:c24"
    "2002:add0:b13a::add0:b13a"
    "2002:add0:c26d::add0:c26d"
    "2002:b95d:bb45::b95d:bb45"
    "2400:5300:0:1:a6ba:dbff:fe40:2967"
    "2a01:238:20a:202:1000::25"
    "2a01:7e01::f03c:91ff:fee4:dc40"
    "2a02:2770:11:0:21a:4aff:fef0:e779"
    "2a02:c200:1:10:2:4:2347:2d"
    "2a03:f81:aaaa:aaaa:ffff:1:69:100"

I don't know who they belong to ;) For unittests you can use addresses from ianaorg, icann.org, example.org and so on.

**Comment by juancb** [comment]
It looks like pyasn_radix assumes all inputs are AF_INET, however it's possible to work around it by passing pyasn_radix functions a packed address.

```
In [84]: radix.search_best('2606:2800:4033:197:914d:27be:f986:bec4')
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-84-55224e98d866> in <module>()
----> 1 radix.search_best('2606:2800:4033:197:914d:27be:f986:bec4')

ValueError: inet_pton() returned error
```

By passing a packed function as a named argument we can circumvent the problem. I'm not sure where else this creeps up as I haven't figured out a way to get pyasn to accept a packed value.

```
In [85]: radix.search_best(packed=socket.inet_pton(socket.AF_INET6, \
 '2606:2800:4033:197:914d:27be:f986:bec4'))
Out[85]: <pyasn_radix.RadixNode at 0x105fd3eb0>
```

**Comment by sebix** [comment]
Any updates on this issue?

**Comment by hadiasghari** [comment]
Hi Sebix, 

I just pushed an update to master that adds IPv6 support. I've tested it successfully on the list of IPs you gave. A new IPASN6 file is also included. Could you kindly test the changes, and confirm that it works for you? Then I'll release it.  

Cheers

**Comment by sebix** [comment]
The code works for me, thanks!

I do not get results for the IPs posted above though.

**Comment by hadiasghari** [comment]
Sebix, they should work. You need to open an ASNDAT file that has IPv6 prefixes in it. I included an example one in the data directory, it's called "ipasn6_20151101.dat".  

I should perhaps add a bit to the manual on how to create these files (you need to download and process RIBs that have IPv6 info, for instance from routeviews4 -- http://archive.routeviews.org/route-views4/bgpdata/2015.11/RIBS/ -- see table for all routeview hosts: http://www.routeviews.org/)

I should also perhaps change the pyasn's representation to show how many v4/v6 prefixes the ipasndat file has.

**Comment by sebix** [comment]
I just tried a newly downloaded file using the pyasn-utils. I can try again next week.

Hence a feature request: Maybe the utility can download two current files, for both IPv4 and IPv6 and the convert tool combines them to one?

**Comment by sebix** [comment]
Yes, it works!

**Comment by hadiasghari** [comment]
@sebix thanks for checking this. I created a new issue to add the ability to download the MRT-RIB files with both IPv4 and IPv6.

**Comment by sebix** [comment]
Could you please upload the 1.5.0b7 to pypi please?

**Comment by hadiasghari** [comment]
Sure, will do this week.

**Comment by hadiasghari** [comment]
Done.

**Comment by sebix** [comment]
great thanks!
