### ISSUE TITLE
Version tags missing

### ISSUE THREAD

**Issue by sebix** [hadiasghari/pyasn#15]
There are no tags indicating where the software has been released as a specific version.

It seems 0c1ae718cd3394b534392533a7f26f837dfd42fc is 1.5.0b6, also on pypi.
af9acfbed0b547afd772fbcfdb2276f5e716fc66 is 1.5.0b5
2d82fcb0b6654d72a10ec8cfc0caf55cfb7f3c7a seems to be 1.5.0b4
bdf743cf9342f9a4c902e32d6f996e5e5b43c4f0 or 75285dd15792b1cc985ffee6491c9d8cf8d29a66 is 1.5.0b3

**Comment by hadiasghari** [comment]
Hi sebix, thanks for pointing this out. We'd forgotten to push them on git  (git push --tags @anoroozian ). I just did that, you should now see them. Please confirm to close the issue.

**Comment by sebix** [comment]
Great, thanks!
