### ISSUE TITLE
Data File License

### ISSUE THREAD

**Issue by chris-barry** [hadiasghari/pyasn#17]
Hi,

Is it safe to assume that the [data files](http://data.3tu.nl/repository/uuid:d4d23b8e-2077-4592-8b47-cb476ad16e12) are under a license similar to the MIT? I would like to ship one of these files with my code and would like to be compliant with the license.

Thanks.

**Comment by hadiasghari** [comment]
Hi Chris-Barry.  
I think it would be a safe assumption; if not even a more liberal license. I am of course not a copyright expert. But my thinking is that the data files are processed versions of the RouteViews BGP dumps of the Internet routing table; the last one (the Internet routing table) should be in the public domain.  
-Hadi

**Comment by chris-barry** [comment]
I'm citing it under the MIT license to be safe :smile:. For reference, the project is here: https://github.com/chris-barry/i2spy
