### ISSUE TITLE
Add ability to downoad other routeview archives (mainly for IPv6)

### ISSUE THREAD

**Issue by hadiasghari** [hadiasghari/pyasn#18]
This issue is a follow up on adding IPv6 functionality. The module now supports IPv6 if the IPASN file given to it has IPv6 prefixes. The pyasn_util_convert can convert/create this if the given MRT-RIB has IPv6 prefixes. pyasn_util_download currently downloads routeview-1 archives which only have IPv4, and the BGP dumps with IPv4/IPv6 prefixes to be downloaded manually (see: www.routeviews.org). It might be good to add an option to add files routeviews-4. The prerequisite is to understand the differences between the routes advertised in these different dumps more clearly to make sure changing the input has no adverse effects.

**Comment by hadiasghari** [comment]
So basically we can split this up in two parts:

First, an option to choose which routeviews server RIB to download, e.g.:
-RV2 (ipv4 only, current): http://archive.routeviews.org/bgpdata/
-RV4 (ipv4+ipv6): http://archive.routeviews.org/route-views4/bgpdata/
-RV6 (ipv6 only): http://archive.routeviews.org/route-views6/bgpdata/
(full list at http://archive.routeviews.org/)

Second, debugging if/how the RV4 and RV2 files differ -- to possibly change the default download  to RV4.  (This task would benefit from adding detailed-dump/debug functionality, or a unit-test,  to pyasn_util_convert.)

Example from 20160831: 
- RV2=655741 prefixes at 108MB
- RV4=692366 prefixes at 78MB  (how many v4, how many v6?)
- RV6=34915 prefixes at 6MB

**Comment by hadiasghari** [comment]
Thanks @jkrauska for adding the --updatev6 switch; so part of this is done.

**Comment by hadiasghari** [comment]
Alright, this is the remainder: 

(i) add also switches  for --latestv4 (which is equivalent to --latest) and --latestv4v6 (which uses routeviews4)
(ii) create a separate issue for the second task (understanding differences between routeviews)

**Comment by jkrauska** [comment]
I could finish part 1 for you.

I'd generally prefer to use an arg parsing tool when you start adding lots of options -- are you ok with argparse (optparse is deprecated)?

**Comment by hadiasghari** [comment]
@jkrauska yes argparse would be perfect. 

@sebix, does it make sense that we also add the RIPE sources (you use in https://intelmq.org/2016/04/27/asn-lookup-made-easy.html) as a download option? Is there any reason you recommend RIPE RIS over RotueViews?

**Comment by sebix** [comment]
> @sebix, does it make sense that we also add the RIPE sources (you use in https://intelmq.org/2016/04/27/asn-lookup-made-easy.html) as a download option? Is there any reason you recommend RIPE RIS over RotueViews?

ping @aaronkaplan

**Comment by aaronkaplan** [comment]
> On 16 Sep 2016, at 20:48, Hadi Asghari <notifications@github.com> wrote:
> 
> @jkrauska yes argparse would be perfect.
> 
> @sebix, does it make sense that we also add the RIPE sources (you use in https://intelmq.org/2016/04/27/asn-lookup-made-easy.html) as a download option? Is there any reason you recommend RIPE RIS over RotueViews?
> 
Absolutely!
RIPE stat is one of the most trusted sources.

**Comment by hadiasghari** [comment]
@aaronkaplan I understand RIPE is a technically trustworthy source, and that enough would be a good reason to include it. 

But to dig into more details: (i) Have you compared the table with routeviews and know of systematic differences? (ii) Does it contain both v4 and v6 routing information?

**Comment by aaronkaplan** [comment]
> On 19 Sep 2016, at 15:57, Hadi Asghari <notifications@github.com> wrote:
> 
> @aaronkaplan I understand RIPE is a technically trustworthy source, and that enough would be a good reason to include it.
> 
> But to dig into more details: (i) Have you compared the table with routeviews and know of systematic differences? (ii) Does it contain both v4 and v6 routing information?
re: (i): No not yet, should be done.
re (ii): yes!

**Comment by hadiasghari** [comment]
@jkrauska thanks,  merged.
@aaronkaplan would be interesting to do a systematic comparison. I'll open another issue for that.
