### ISSUE TITLE
Add method to get as size

### ISSUE THREAD

**Issue by hadiasghari** [hadiasghari/pyasn#19]
Suggested by Arman.

for-ipv4 this is: sum([2**(32-int(s.split('/')[1]))  for i in prefixes])

**Comment by hadiasghari** [comment]
@anoroozian is this done? can I close this?

**Comment by anoroozian** [comment]
@hadiasghari 
Hadi, I've this implemented locally for IPv4. I'm going to also write some tests and push the changes this week. Maybe we should also discuss a similar function for IPv6.

**Comment by sebix** [comment]
You may want to reuse the functionality of the [ipaddress](https://docs.python.org/3/library/ipaddress.html) module:
```python
>>> import ipaddress
>>> ipaddress.IPv4Network('192.168.0.0/24')
IPv4Network('192.168.0.0/24')
>>> ipnet = ipaddress.IPv4Network('192.168.0.0/24')
>>> ipnet.num_addresses
256
```

Available as standard lib in >= 3.3, otherwise it's available as [pypi-module](https://pypi.python.org/pypi/ipaddress/1.0.17).

**Comment by anoroozian** [comment]
@hadiasghari @sebix, thanks. 
I pushed my code  but I don't want to close the issue yet.

In terms of maintainability and code aesthetics I agree with @sebix. Reusing the IPv4Network class is the more elegant solution. But I also need to keep an eye on performance.

Our own usage of pyasn sometimes involves millions of calls to functions of the pyasn class and I'm leaning a bit towards avoiding object creation and the extra method call.

I'll profile the performance of the two alternatives before I close this issue.

**Comment by sebix** [comment]
Calling ipaddress is of course unrewarding. But you can take a look at their implementation.(Starting [here](https://hg.python.org/cpython/file/3.5/Lib/ipaddress.py#l720))

**Comment by hadiasghari** [comment]
Ping @anoroozian.

**Comment by hadiasghari** [comment]
I'm closing this due to little interest at the moment, please feel free to reopen it.
