### ISSUE TITLE
get_as_name

### ISSUE THREAD

**Issue by imaia** [hadiasghari/pyasn#21]
As of now, get_as_name is a "DO NOT USE YET" method. Would a implementation using http://www.cidr-report.org/as2.0/autnums.html for a lookup be good enough for it? If so, I could do it.

**Comment by hadiasghari** [comment]
Yes that would be a great solution.

**Comment by italomaia** [comment]
Here you go https://github.com/hadiasghari/pyasn/pull/24

**Comment by hadiasghari** [comment]
Thank you, will have a look later this week.

**Comment by hadiasghari** [comment]
@italomaia thanks, it looks great.
My only consideration is the dependency on parsel. Can we relax that requirement? I prefer to avoid additional dependencies, unless absolutely necessary

**Comment by imaia** [comment]
As pyasn has very few requirements, I felt this could be an issue. I'll try to make do without parsel and update the pull request. autnums "format" most likely won't change at all over time, so, it should work.

**Comment by italomaia** [comment]
https://github.com/hadiasghari/pyasn/pull/24

**Comment by anoroozian** [comment]
Implemented ...
see https://github.com/hadiasghari/pyasn/pull/24
