### ISSUE TITLE
utils as callables

### ISSUE THREAD

**Issue by imaia** [hadiasghari/pyasn#22]
It would be great to use pyasn utils, convert and download as callables. Is that a feature desired by more people?

**Comment by hadiasghari** [comment]
@imaia if you happen to make the changes, please submit a pull request, it could be useful for also testing.

**Comment by hadiasghari** [comment]
In the latest upload to master, I refactored 'pyasn_util_download.py'  so one can now call methods to download the latest route-views files, e.g.:

    # import ...
    srvr, rp, fn = find_latest_routeviews(4)
    ftp_download(srvr, rp, fn, fn)

'pyasn_util_convert.py' already called methods (in mrtx.py) for the conversion, they are also simplified, e.g.:
 
    # import ...   
    prefixes = parse_mrt_file('rib-dump.bz2') 
    dump_prefixes_to_file(prefixes, 'ipasn.dat')

**Comment by JustinAzoff** [comment]
Thanks for adding this, I was about this sort of thing only to see that it was just completed!

**Comment by JustinAzoff** [comment]
Hmm, on a closer look this is 99% there but one small issue prevents it from being more useful.  The utils are in a pyasn-utils directory that does not have an __init__.py so they can't be directly imported with something like

    from pyasn.utils import download

Currently I'm using a lot of subprocess calls to download and convert the data.  You can see what I'm doing here:

https://github.com/JustinAzoff/asnlookup/blob/master/asnlookup/data_manager.py#L82

**Comment by hadiasghari** [comment]
@JustinAzoff  that's a great point which I overlooked. Is the __init__ something you could add, perhaps with also a unit-test?

**Comment by JustinAzoff** [comment]
Yes.. I can look into it.  The directory will need to be renamed though, because you can not 'import pyasn-utils'.

I think the gist of it would just be

    git mv pyasn-utils utils
    touch utils/__init_.py

and then fixup setup.py and write the tests.  I will see about doing this tomorrow.

**Comment by hadiasghari** [comment]
That's a good point about the directory name. Perhaps it's better then to add a utils.py under pyasn, so the import statement can be ```from pyasn import utils``` ... instead of  ```import utils```. We then move the key methods from the ```pyasn_util*``` files into it, and also some methods from your ```data_manager.py```.

**Comment by JustinAzoff** [comment]
Yeah.. I realized I utils belonged under pyasn/ once I started. I just pushed out a first pass of this, it looks like it works:

API:

```
>>> from pyasn.utils import download
>>> download.find_latest_routeviews('4')
Connecting to ftp://archive.routeviews.org
Finding most recent archive in /bgpdata/2017.01/RIBS ...
('archive.routeviews.org', '/bgpdata/2017.01/RIBS', 'rib.20170110.1400.bz2')
>>>
```
CLI:
```
$ pyasn_util_download -4
Connecting to ftp://archive.routeviews.org
Finding most recent archive in /bgpdata/2017.01/RIBS ...
Downloading ftp://archive.routeviews.org//bgpdata/2017.01/RIBS/rib.20170110.1400.bz2

```

It's in https://github.com/JustinAzoff/pyasn/tree/importable-utils as https://github.com/JustinAzoff/pyasn/commit/aa7f5e1ae8c784b4c60286115434c7e7a65d70c9

It looks like a very large commit, but it's almost all whitespace changes.  The biggest change is probably switching from scripts to console_scripts in setup.py.

It probably makes sense to change the various 'args' functions to take keyword arguments, so one could do

```
pyasn.utils.convert(single=...)
```

**Comment by JustinAzoff** [comment]
Hi, got sidetracked for a bit but working on finishing this.  I refactored convert.py a bit further to see how it would look using regular keyword arguments:

https://github.com/JustinAzoff/pyasn/commit/6ca5b87ef69b83e7190dce3edc1a5e340371141b

The primary change was changing `main` to

```
    args = parser.parse_args()
    args_dict = vars(args)
    return main(**args_dict)
```

and then updating the definition and removing references to `args.`

This lets you:

```
>>> from pyasn.utils import convert
>>> convert.main(single=["rib.20170124.2000.bz2", "out.out"])
Parsing MRT/RIB archive ..  MrtTD2Record (PEER-INDEX-TABLE, collector 2162111334, 68 peers)
  WARNING: repeated prefix '5.10.225.0/24' maps to different origin (3194 vs 201272)
  WARNING: repeated prefix '5.10.230.0/24' maps to different origin (3194 vs 201272)
  WARNING: repeated prefix '38.67.212.0/22' maps to different origin (174 vs 394540)
  WARNING: repeated prefix '38.133.64.0/22' maps to different origin (174 vs 394540)
  MRT record 100000 @21s
  MRT record 200000 @41s
  WARNING: repeated prefix '103.19.170.0/23' maps to different origin (131214 vs 38809)
  WARNING: repeated prefix '103.19.171.0/24' maps to different origin (131214 vs 38809)
  MRT record 300000 @58s
  MRT record 400000 @78s
  MRT record 500000 @96s
  WARNING: repeated prefix '202.73.25.0/24' maps to different origin (55701 vs 132653)
  WARNING: repeated prefix '202.73.26.0/24' maps to different origin (55701 vs 132653)
  WARNING: repeated prefix '203.32.185.0/24' maps to different origin (55871 vs 17755)
  MRT record 600000 @114s
IPASN database saved (680969 IPV4 + 0 IPV6 prefixes)
>>>
```

As next steps, I think the prints should be converted to logging statements and the function should return something - like the prefix counts.
