### ISSUE TITLE
binary representation

### ISSUE THREAD

**Issue by j---** [hadiasghari/pyasn#26]
Investigate using Silk and pysilk with the available binary IP-to-ASN mapping for the binary representation.
http://tools.netsa.cert.org/silk-ipset/docs.html
https://tools.netsa.cert.org/silk/pysilk.html
http://routeviews-mirror.cert.org/pmap/
Specifically, use this object type to manipulate the available historical files:
https://tools.netsa.cert.org/silk/pysilk.html#PrefixMap-Object

Will need to be careful to be backwards compatible and not introduce (too many) dependencies.

**Comment by hadiasghari** [comment]
@j---  thanks.. I support the endeavor of  adding functionality to load the Silk IP-ASN-mappings (with optional dependencies). I'm busy in the next two weeks or so and can join you in the thinking after that.

**Comment by hadiasghari** [comment]
@j--- so what's the best way to move forward on this...

**Comment by hadiasghari** [comment]
@j--- so here are some thoughts, based on our earlier discussion:

1- The most interesting integration IMO is to allow pyasn to consume pmap files (http://routeviews-mirror.cert.org/pmap/). This can be either by extending `pyasn.pyasn()` to directly read pmap, or extending `pyasn_util_convert` to convert them to ipasndat format.

2-  I wouldn't want to introduce new dependencies to pyasn. So we would need to extract the minimum necessary parts from SiLK's Python or C code. Do you know which/how many files this is? 

Thanks.

**Comment by hadiasghari** [comment]
Update: I plan to deprecate mrtx.py/dump_prefixes_to_binary_file() , and instead add the ability to read GZIP files in pyasn.c's loader. This will be more coherent and require less testing than adding a new file format. 

The implementation will either use [Zlib](http://www.zlib.net/manual.html) in C, or we will do the unzipping in python and pass a string to the C function.  

The ability to read SiLK's files will be great to still have, once we  figure out the minimum dependency issue (@j---).

**Comment by hadiasghari** [comment]
@j--- I will close this for now, since there has been little update/interest. Feel free to reopen it.
