### ISSUE TITLE
pyasn_util_convert: Support for gzip

### ISSUE THREAD

**Issue by sebix** [hadiasghari/pyasn#27]
[RIPE data](https://www.ripe.net/analyse/internet-measurements/routing-information-service-ris/ris-raw-data) is gzip-compressed, thus direct support for it would be nice.

[Usage example](https://intelmq.org/2016/04/27/asn-lookup-made-easy.html)

**Comment by hadiasghari** [comment]
This is a great idea. The main challenge is finding a cross-platform library in C for the GZip part.

**Comment by sebix** [comment]
Why not use the [gzip module](https://docs.python.org/3/library/gzip.html)?

**Comment by hadiasghari** [comment]
It's rather slow to read and load the database in Python, and the loading happens in the C code.

**Comment by sebix** [comment]
I thought of adding the functionality to the conversion-tool, is there more needed?

**Comment by hadiasghari** [comment]
@sebix I thought you meant for the ipasn.dat files. Do you mean that?

**Comment by sebix** [comment]
See the already provided link: https://intelmq.org/2016/04/27/asn-lookup-made-easy.html

To read data from ripe.net, it is needed to convert the data from gzip to bunzip before converting, because the convert utility does not understand gzip.

**Comment by hadiasghari** [comment]
Ah I see. That should be pretty easy then: pyasn-util-convert needs to do `gzip.open() ` instead of  `bz2.BZ2File()` in a number of places based on the file extension.

**Comment by jkrauska** [comment]
The mrtparse code does this pretty elegantly.

https://github.com/YoshiyukiYamauchi/mrtparse/blob/master/mrtparse/__init__.py

Search for MAGIC.

**Comment by hadiasghari** [comment]
@jkrauska thanks, that is pretty neat indeed
