### ISSUE TITLE
fix pyasn __init__ to work with py27

### ISSUE THREAD

**Issue by sanketsharma411** [hadiasghari/pyasn#31]
In commit https://github.com/hadiasghari/pyasn/commit/65b9576a35f4ef2ee84da6c925da851e07dc458b, ```open(..., encoding=...)``` was used which would not work with python < 3. Instead as  suggested ```codecs.open()``` should be used, which would be consistent with python 2.7 and 3.

**Comment by sebix** [comment]
@hadiasghari could you cherry-pick this commit?

**Comment by hadiasghari** [comment]
Thanks @sanketsharma411 @sebix , will check it this weekend.

**Comment by hadiasghari** [comment]
@sebix alright, done, please reopen if there is an issue.
@sanketsharma411 thank you for the patch!
