### ISSUE TITLE
Error message with RIPE Otemachi data

### ISSUE THREAD

**Issue by johanmazel** [hadiasghari/pyasn#43]
I am trying to convert some RIB data from RIPE Otemachi (http://data.ris.ripe.net/rrc06/).

I am getting this error message:
Traceback (most recent call last):
  File "pyasn_util_convert.py", line 81, in <module>
    prefixes = mrtx.parse_mrt_file(f, print_progress=not args.no_progress)  # also skip-on-error=T?
  File "/usr/local/lib/python2.7/dist-packages/pyasn-1.5.0b8-py2.7-linux-x86_64.egg/pyasn/mrtx.py", line 89, in parse_mrt_file
    origin = mrt.get_first_origin_as()
  File "/usr/local/lib/python2.7/dist-packages/pyasn-1.5.0b8-py2.7-linux-x86_64.egg/pyasn/mrtx.py", line 314, in get_first_origin_as
    return path.get_origin_as()
  File "/usr/local/lib/python2.7/dist-packages/pyasn-1.5.0b8-py2.7-linux-x86_64.egg/pyasn/mrtx.py", line 562, in get_origin_as
    assert self.pathsegs[0].seg_type == self.BgpPathSegment.AS_SEQUENCE
IndexError: list index out of range

Files that generate this error are:
bview.20030701.0000.gz
bview.20050701.0000.gz
bview.20060701.0000.gz
bview.20070101.0000.gz
bview.20070701.0759.gz
bview.20080101.0000.gz
bview.20080701.0759.gz
bview.20090101.0759.gz
bview.20090701.0759.gz
bview.20100101.0759.gz
bview.20100701.0759.gz
bview.20110101.0000.gz
bview.20110701.0000.gz
bview.20120201.0000.gz
bview.20120701.0000.gz
bview.20130101.0000.gz
bview.20130701.0000.gz
bview.20140101.0000.gz
bview.20140701.0000.gz
bview.20150101.0000.gz

**Comment by hadiasghari** [comment]
Hi @johanmazel, I've added a new '--skip-on-error' switch to 'pyasn_util_convert' in the latest source. 

Please get it and test with that to see which prefixes/records have errors, and convert without them. 

If this suffices, please close the issue, otherwise, add some more details (the new --dump-screen option might help here).  Cheers

**Comment by johanmazel** [comment]
When I do "python pyasn_util_convert.py --skip-on-error --single ripe_otemachi_rib/bview.20030701.0000.gz ripe_otemachi_dat/ipasn_20030701_0000.dat", I get this eror:
usage: pyasn_util_convert.py [-h]
                             (--single RIBFILE IPASN.DAT | --dump-screen RIBFILE | --bulk START-DATE END-DATE | --version)
                             [--no-progress] [--limit-to N]
pyasn_util_convert.py: error: unrecognized arguments: --skip-on-error

When I do "python pyasn_util_convert.py --dump-screen ripe_otemachi_rib/bview.20030701.0000.gz", I get this:
Traceback (most recent call last):
  File "pyasn_util_convert.py", line 93, in <module>
    mrtx.dump_screen_mrt_file(f, limit_to=args.limit_to, screen=stdout)
TypeError: dump_screen_mrt_file() got an unexpected keyword argument 'limit_to'

Am I missing something ?

**Comment by hadiasghari** [comment]
Get the latest version (1.6b) from master.

**Comment by johanmazel** [comment]
When I do "python pyasn_util_convert.py --skip-on-error --single ripe_otemachi_rib/bview.20030701.0000.gz ripe_otemachi_dat/ipasn_20030701_0000.dat", I get:
  WARNING: can't get_origin_as for prefix 195.80.230.0/24
IPASN database saved (126393 IPV4 + 0 IPV6 prefixes)

"pyasn_util_convert.py --dump-screen ripe_otemachi_rib/bview.20030701.0000.gz | grep -A 4 195.80.230.0/24" yields:
Record #056560: MrtTD1Record (IPV4 195.80.230.0/24, attributes 21B)
		 BGPAttribute(ORIGIN): 0
		 BGPAttribute(AS_PATH): path-
		 BGPAttribute(NEXT_HOP): 0
		 BGPAttribute(MULTI_EXIT_DISC): 0

**Comment by hadiasghari** [comment]
@johanmazel is this a major issue? Or a one off case with the particular record in the file above?  I am closing the issue for now, if it remains a major problem, please reopen it with more examples. Cheers.
