### ISSUE TITLE
Question about IP Network Relationships

### ISSUE THREAD

**Issue by masterseo2000** [hadiasghari/pyasn#44]
Hello,
looks like a great tool. I was wondering if it shows the IP owner relationships (downstream/upstream provider relationships)? If anyone has an idea on how to map those relationships I would really appreciate it.
Thanks a lot

**Comment by hadiasghari** [comment]
Hi @masterseo2000. pyasn will tell you the autonomous-system that owns the IP address. 

Here are a few resources for downstream/upstream ASes:
- Internet AS level topology (http://irl.cs.ucla.edu/topology/)
- CAIDA (http://www.caida.org/research/topology/)

Cheers
