### ISSUE TITLE
compilation error on Windows

### ISSUE THREAD

**Issue by gsankara** [hadiasghari/pyasn#47]
C:\Users\abcd\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.
0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Users\abcd\tracert\pyasn-1.6.0b1\pyasn -Ic:\Python27\include -Ic:\Python27\PC /Tcpyasn/pyasn_radix.c /Fobuild\temp.win32-2.7\Release\pyasn
/pyasn_radix.obj
pyasn_radix.c
pyasn/pyasn_radix.c(662) : error C2143: syntax error : missing ';' before 'type'

When I moved the corresponding declaration from line 662 to as the first statement within the block i.e. 656, it got compiled successfully.
char buf[512], *p1, *p2;

**Comment by hadiasghari** [comment]
Hi @gsankara , thanks for this. Can you do a pull request with your fix? I can then merge it ot the main code.

**Comment by gsankara** [comment]
Sorry @hadiasghari. I am not familiar with the procedure you are suggesting.

regs
Ganesh

**Comment by hadiasghari** [comment]
It's rather simple: you fork pyasn on github, make your changes and commit to your forked repository, then do a pull request through the github interface so I can merge it. I can then test+merge it.

**Comment by gsankara** [comment]
@hadiasghari Thanks, done. Please check if it is okay.

regs
Ganesh

**Comment by hadiasghari** [comment]
Thank you, I've merged your changes in master!
