### ISSUE TITLE
Getting an organization name from ASN

### ISSUE THREAD

**Issue by seanthegeek** [hadiasghari/pyasn#53]
Is it possible to get an organization name from ASN offline?

**Comment by hadiasghari** [comment]
Hi @seanthegeek, pyasn doesn't  currently do that. There are online lists of AS names, for instance: 

http://bgp.potaroo.net/cidr/autnums.html
http://www.bgplookingglass.com/list-of-autonomous-system-numbers

Also, MaxMind has a database for doing it offline.

**Comment by gabrielmocan** [comment]
Wasn't that feature implemented on #24 ?

**Comment by hadiasghari** [comment]
@gabrielmocan thanks for the correction, I had totally forgotten that. I'll edit my answer.

**Comment by gabrielmocan** [comment]
You're welcome @hadiasghari. And I have to admit, it works like a charm!
