### ISSUE TITLE
wheel available somewhere?

### ISSUE THREAD

**Issue by randomgambit** [hadiasghari/pyasn#57]
I realize the package needs the visual studio C++ building tools.

I - like many others - cant install it on my computer at work. I have checked on the pre-compiled binaries here https://www.lfd.uci.edu/~gohlke/pythonlibs/#wordcloud but unfortunately `pyasn` is not there.

Could you perhaps please provide a `wheel` of the package for python 3. ?
Is this possible?

Thanks!

**Comment by hadiasghari** [comment]
If anyone does this I'll be happy to support it. Otherwise I refer to #58 for a workaround.
