### ISSUE TITLE
Web service wrapper and database manager extension

### ISSUE THREAD

**Issue by 9b** [hadiasghari/pyasn#60]
Thank you for providing this library! 

I recently decided to use this module within a project of mine in order to enrich IP addresses that I extracted from logs. During setup, I noticed that the service would be best represented as an API, so I wrapped a small Flask application around the library. I also noticed that while there are utilities to manage downloading incremental updates, there's no easy way to keep a working database up-to-date without user interaction. 

To address these challenges, I've wrapped PyASN into a service called NetInfo and opensourced it. I wasn't sure if you'd want this sort of code in the repository, but if there's interest, let me know and we can work together. 

**Project details:**
https://github.com/9b/netinfo

**Write-up:**
https://medium.com/@9bplus/netinfo-free-enrichment-for-ip-addresses-ecbcd62e43b6

**Comment by hadiasghari** [comment]
Hi Brandon @9b thanks for the link and the writeup. There are nice extensions and potentially useful to others. Is it possible in your opinion to integrate the web API & continous downloader without having to make them mandatory extensions—since not everyone might want them and I don't like to add dependencies to the module?

**Comment by 9b** [comment]
I think we could, similar to how you have utilities for downloading. What I might be able to do is build a small utility that downloads the source from netinfo and sets everything up. A low-friction approach would be to link to netinfo for those wishing to host a webserver copy.

**Comment by hadiasghari** [comment]
Hi @9b, do you want to do add a small section to the README regarding the netinfo project? Or some other low-dependency option that I can look into merging via a PR? For now I am closing this. Cheers.
