### ISSUE TITLE
PYASN use for private enterprise BGP 

### ISSUE THREAD

**Issue by netwninja** [hadiasghari/pyasn#61]
I'm trying to setup pyasn for private BGP AS and prefix co relation. I tried tweaking the prefix database downloaded from internet by adding RFC1918 prefixes and private AS numbers. 
however, it didn't work. 

Is it possible to use pyasn for private BGP setup ? If yes, is there a doc available using which we can try to create a private BGP AS and Prefix database ?

Thanks 
GS

**Comment by hadiasghari** [comment]
Hi @netwninja, the MRT parser discards private BGP ASes from the AS Path as this causes issues in most cases. You would need to make changes to the code for your purpose. Have a look at the `is_asn_bogus` function in `mrtx.py`.
