### ISSUE TITLE
Request for New PyPi Release?

### ISSUE THREAD

**Issue by jasonma97** [hadiasghari/pyasn#63]
Hi, I was wondering if it would be possible for you to make a new pypi release with the changes you've made to the master branch. 

My code is currently breaking when using the current pypi release of pyasn, and it seems that the changes you've made (namely the asn ranges in `asn_is_bogus`) resolve the issues.

**Comment by hadiasghari** [comment]
Hi @jasonma97, this is a good idea, I'll look into doing a new release in the coming weeks.

**Comment by jasonma97** [comment]
Hi @hadiasghari, just wanted check to see if there are any updates to this?

**Comment by hadiasghari** [comment]
I was hoping to get a new project maintainer on board but I haven't succeeded yet. :) I'll have a look at releasing a new version later this week.

**Comment by hadiasghari** [comment]
Dear @jasonma97 I have released a new version, could you check and tell me if it works as expected? Thanks.

**Comment by hadiasghari** [comment]
This should be working similar to #62, which was recently closed. If still an issue please reopen.
