### ISSUE TITLE
IPv6 Prefixes do not downloaded on RIB/DB file

### ISSUE THREAD

**Issue by thamayron** [hadiasghari/pyasn#65]
Hello guys,

how have you been?

I'm a network engineering and I'm developing a tool with python and django to make my team easier, so I don't know if I'm making some mistake or if the file really does not have IPv6 addresses or some bug.

**I hope you can help me.**

After the instalation, I'm generating my db file and when I open it there is no IPv6 address on it.

I ran this commands do download and convert my DB, but 

![image](https://user-images.githubusercontent.com/13776577/91651024-9de35180-ea5d-11ea-956c-8a16c5eb419e.png)

![image](https://user-images.githubusercontent.com/13776577/91651027-a50a5f80-ea5d-11ea-94f5-f79f5ba45fc8.png)

![image](https://user-images.githubusercontent.com/13776577/91651030-a76cb980-ea5d-11ea-847d-c6c4d28eb521.png)

When I run some code I got "None" as the "value".

![image](https://user-images.githubusercontent.com/13776577/91651121-05e66780-ea5f-11ea-85d1-a9ebb4ba1e87.png)

![image](https://user-images.githubusercontent.com/13776577/91651122-08e15800-ea5f-11ea-8187-210fda2b24fa.png)

And when I go to whois br , I found IPv6 addressess

https://registro.br/tecnologia/ferramentas/whois/?search=as16735

![image](https://user-images.githubusercontent.com/13776577/91651124-0e3ea280-ea5f-11ea-9bfa-e56ff9fff26a.png)

**Comment by hadiasghari** [comment]
Hi @thamayron. Please try either `--latestv6`  or `--latestv46` argument with `pyasn_util_download`. The default MRT/RIB file downloaded, if I recall correctly, only has IPv4 routes.

**Comment by thamayron** [comment]
**It works! Thank you very much Hadi (@hadiasghari) , it will help me a lot!**

![image](https://user-images.githubusercontent.com/13776577/91664944-cce2dd00-eac8-11ea-846a-e1eb3fcd94d9.png)

![image](https://user-images.githubusercontent.com/13776577/91664966-eb48d880-eac8-11ea-95c1-263950513b6a.png)


Just for information, do you intend to do name translation  ?

**Comment by hadiasghari** [comment]
I'm glad it helped. I've updated the README to make it clear for others as well. Regarding name-translation, there are no plans for it at this moment.

**Comment by thamayron** [comment]
Thank you very much!
