### ISSUE TITLE
Link to previously-generated IPASN files is dead

### ISSUE THREAD

**Issue by strikaco** [hadiasghari/pyasn#66]
> We also provide download links to a large number of previously generated IPASN data files. These are based on weekly snapshots of the Routeviews data from 2005-2015, accessible here: https://www.narcis.nl/dataset/RecordID/uuid:d4d23b8e-2077-4592-8b47-cb476ad16e12

For the sake of awareness, this link only returns a 404.

**Comment by hadiasghari** [comment]
Thanks, I'll updated it to this: https://doi.org/10.4121/uuid:d4d23b8e-2077-4592-8b47-cb476ad16e12 
Please tell me if this works

**Comment by strikaco** [comment]
Thanks for the quick response! The link does work and I successfully downloaded a 650MB archive of RIBs from it.

If it's worth following up on at all, the verbiage on the new page is a little misleading though:

> This data enables you to perform offline IP address to Autonomous System Number lookups for any point in time.

...any point in time, as long as it's between 2005 and 2015 ;)

**Comment by hadiasghari** [comment]
It works for any time, but you need to create the IPASNDAT file yourself. To do that you download an MRT-RIB file using `pyasn_util_download.py` and convert it with `pyasn_util_convert.py`.
