### ISSUE TITLE
Impossible to import after the installation in python 3.6.8

### ISSUE THREAD

**Issue by khaledazrak** [hadiasghari/pyasn#67]
Hi, just installed it with the tar.gz file, seems everything ok.

But when trying to import it in python 3.6.8, i have this error :  

>>> import pyasn
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/pyasn-1.6.1/pyasn/__init__.py", line 21, in <module>
    from .pyasn_radix import Radix
ModuleNotFoundError: No module named 'pyasn.pyasn_radix'
```

**Comment by hadiasghari** [comment]
Hi @khaledazrak , the advised way to install pyasn is via `pip install pyasn`. 
Can you explain what platform you are using,  and how you have exactly installed the tar.gz file?

**Comment by hadiasghari** [comment]
I'm assuming this issue is resolved; if not feel free to repoen.
