### ISSUE TITLE
Pickle Persistence Error

### ISSUE THREAD

**Issue by mansweet** [hadiasghari/pyasn#68]
Hello,
First and foremost, thanks for writing this library and providing it to the community. I really appreciate the hard work you've done in research for it, as well as the thorough testing.  Having a fast lib for looking up IP ASN's is important to our application. 

I'm trying to use the `pyasn` lib in a spark application and would like to make it a broadcast variable, that way I only have to load it once instead of several times.  Using a PySpark broadcast variable requires that it gets pickled.  PySpark uses the cpickle lib.

I've run an experiment trying to pickle the pyasn object with vanilla pickle without any Spark, and get the following error:
```AttributeError: 'pyasn_radix.Radix' object has no attribute '__dict__'```

When PySpark tries to read the broadcast variable, it throws:
```   return pickle.load(file)
cPickle.UnpicklingError: state is not a dictionary
```
... The first error is more informative. 

I notice that you mean well and have a `TODO` for testing this, but looking at the tests, I did not yet see one.  I would submit a PR myself to fix this, but I am not versed in cpython to modify the Radix class. 
https://github.com/hadiasghari/pyasn/blob/87503e6caee036ca4e60f0febaba9335201ac1b7/pyasn/__init__.py#L167

Thanks in advance for considering this change.

**Comment by hadiasghari** [comment]
Hi @mansweet, I committed a new version to Github. Can you pull and run it directly to see if it resolves the problem?

**Comment by hadiasghari** [comment]
I believe this is fixed; if not please feel free to repoen th eissue.
