### ISSUE TITLE
Add support for download rib as `filename` OR add pipeline support for immediately converting downloaded file, regardless of filename

### ISSUE THREAD

**Issue by nermin99** [hadiasghari/pyasn#70]
Sorry for the title. What I'm trying to achieve is an automated process of donwloading the rib file and then converting it, without having to manually input it's name, which will _continuously_ change!

So then I could have an automated script like 
`python pyasn_util_download.py --latest "rib.bz2"
&& python pyasn_util_convert.py --single rib.bz2 ipasn_db_file_name.dat`

OR

something like
`python pyasn_util_download.py --latest | python pyasn_util_convert.py ipasn_db_file_name.dat`

**Comment by hadiasghari** [comment]
Hi @nermin99, I understand the request and it's logical. Your first solution also seems quite easy to implement since it needs one additional parameter for the script. Are you yourself interested in sending a pull request for it?

**Comment by nermin99** [comment]
Yes here you 👍🏻 #71

**Comment by hadiasghari** [comment]
Thank you, I accepted and merged the PR. Do you also need me to do a new Pypi release or are you running/installing from source?

**Comment by nermin99** [comment]
No I'm good, I'm just using the source files

**Comment by tbennett6421** [comment]
Can we get an updated build on pypi that contains this FR?
