### ISSUE TITLE
Request for New PyPi Release

### ISSUE THREAD

**Issue by tbennett6421** [hadiasghari/pyasn#73]
Can we get an updated package on pypi from master, specifically to bring in #70
Very useful for some automation I'm doing. Thank you

**Comment by tbennett6421** [comment]
curious if there's been any movement on this?

**Comment by mzpqnxow** [comment]
Another gentle poke on this

For now I'm using `git+https://github.com/hadiasghari/pyasn@master#egg=pyasn` in setup.cfg when it's a dependency for a package of mine. Would love to get rid of this, especially as it allows me to utilize a caching on-site PyPi mirror

**Comment by hadiasghari** [comment]
Hi @tbennett6421 and @mzpqnxow ... I just uploaded the 1.6.2 version. Could you kindly have a look and test to see if it works?

**Comment by tbennett6421** [comment]
Thank you. I appreciate it
