### ISSUE TITLE
AssertionError while converting RIB

### ISSUE THREAD

**Issue by ct-wei** [hadiasghari/pyasn#76]
I just found the error when I try to convert the rib to dat.
`mrtx.dump_prefixes_to_file(prefixes, args.single[1], args.single[0])
fw.write('; IP-ASN32-DAT file\n; Original source: %s\n' % source_description)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 60-61: ordinal not in range(128)
`

it seems the older rib data can work perfectly, while the new rib data can't. 
like:
`rib.20230803.2200.bz2`
Is it the data's wrong or code bug?

**Comment by hadiasghari** [comment]
Hi @ct-wei. Can you provide some extra information to help with troubleshooting/replication: 

- (i) how/where did you download the file from? 

- (ii) what command did you exactly use for the conversion?

**Comment by ct-wei** [comment]
> 
rib data is from http://archive.routeviews.org/route-views6/bgpdata/2023.08/RIBS/
the command is 
`pyasn_util_convert.py --single rib.20230803.2200.bz2 test.dat`

**Comment by hadiasghari** [comment]
That file and command work without any problems for me--here is my output: 

```
$ pyasn_util_convert.py --single rib.20230803.2200.bz2 test.dat
Parsing MRT/RIB archive ..  MrtTD2Record (PEER-INDEX-TABLE, collector 2162111344, 74 peers)
  MRT record 100000 @4s
  MRT record 200000 @9s
IPASN database saved (0 IPV4 + 200024 IPV6 prefixes)
```

Perhaps try downloading the RIB file again. If it's still not resolved, please tell me your Python & pyasn versions.

**Comment by ct-wei** [comment]
> That file and command work without any problems for me--here is my output:
> 
> ```
> $ pyasn_util_convert.py --single rib.20230803.2200.bz2 test.dat
> Parsing MRT/RIB archive ..  MrtTD2Record (PEER-INDEX-TABLE, collector 2162111344, 74 peers)
>   MRT record 100000 @4s
>   MRT record 200000 @9s
> IPASN database saved (0 IPV4 + 200024 IPV6 prefixes)
> ```
> 
> Perhaps try downloading the RIB file again. If it's still not resolved, please tell me your Python & pyasn versions.

Oh it seems work.Thanks a lot!😊
