### ISSUE TITLE
Version mismatch between git source and pypi releases

### ISSUE THREAD

**Issue by grawlinson** [hadiasghari/pyasn#80]
Hi!

I see the version on PyPi is 1.6.2 and the git source is 1.6.1, are you able to sync up the versions (i.e. push latest code changes to git as well as adding a git tag), if possible?

Thank you for this neat little package. :)

**Comment by hadiasghari** [comment]
Hi @grawlinson, the version is correct here: pyasn/_version.py.
Where do you find 1.6.1 still mentioned? 

-Hadi

**Comment by grawlinson** [comment]
There is no git tag for 1.6.2 as shown [here](https://github.com/hadiasghari/pyasn/tags), yet there is a 1.6.2 release on [PyPi](https://pypi.org/project/pyasn/1.6.2/)

**Comment by hadiasghari** [comment]
Okay I added a tag for the related commit (it was Sep 2023). Please tell me if this works?

**Comment by hadiasghari** [comment]
I assume the issue is resolved. Feel free to reopen if not.
